### ISSUE TITLE
[Feature Request]Add In-game config to the Fabric version of this mod

### ISSUE THREAD

**Issue by tankyap** [ToroCraft/ToroHealth#130]
So I find out that this mod doesn't have a In-game config, which a feature that can let you config while the game is opening.A mod called, [Mod menu](https://www.curseforge.com/minecraft/mc-mods/modmenu)(For Fabric version only), would do the job.
Feel free to add it if you wanted.

**Comment by frodare** [comment]
Yes, that is actually on purpose.  I was using ModMenu in early versions, along with a library to handle the config GUI, however it made the upgrade process more difficult when new MC versions released. Then wanting to support a Forge version made it much worse.  So I opted to keep the project more maintainable at the cost of losing the in-game config.  In some ways the file config version is better, since it updates the game in real time making it easier to move the GUI elements around without needing to constantly open and close config menus.  However, I understand the annoyance it added having to find the file and figure out the correct codes (a problem I am planning to easier however).
