### ISSUE TITLE
ModMenu settings integration

### ISSUE THREAD

**Issue by pjdevs** [ToroCraft/ToroHealth#134]
I would like to add (re-add? sorry but I am new to this mod and can't figure out if GUI settings were present and removed) [ModMenu](https://github.com/TerraformersMC/ModMenu) integration as it would be very nice to configure mod's settings.
If the author is ok with this feature I work on it.

**Comment by frodare** [comment]
I do not want to integrate modmenu + gui config as it makes more work when upgrading MC versions and is not supported in Forge.

However, that doesn't mean it can't be done.  An integration mod could be created to add the GUI config for ToroHealth.   That would allow the mods to be updated independently. It should be pretty easy since it would just need to update the config file and the config file watches for changes.  This is something I could look into in the future, however I am unfortunately too busy right now to start it.
