### ISSUE TITLE
Questions Posted by PCGaming247

### ISSUE THREAD

**Issue by frodare** [ToroCraft/ToroHealth#21]
**_The only problem I find with yours is that  X, Y cords for moving health don't work. 
Mobs animations ether are right on the border of screen or part of them are going off the screen._** 

Please upload a screen shot of this happening and the offset numbers you are using

**_Would it be possible to make a GUI like in BetterPVP mod that you can just drag the health and the Potion Effects to other areas of the screen?_**

That sounds real cool, but unless one of the developers gets an itch to do it or someone provides a PR fro that feature it is not likely to happen.

**_Also I see no way to move the potion effects, I have looked and tried the in game Mod Options and the config file._** 

The mod doesn't have potion effects, maybe you are seeing the vanilla ones that were added in later versions of MC.

**_One last thing if there was a setting to adjust the damage number and how it comes off the entity that would be cool too._** 

What settings do you have in mind?

_**Also if you could add a font for the numbers that has a border around if that would make them more legible.**_

The numbers that come off the entity?

https://mods.curse.com/mc-mods/minecraft/245733-torohealth-damage-indicators?comment=47

**Comment by PCGaming247** [comment]
The only problem I find with yours is that X, Y cords for moving health don't work.
Mobs animations ether are right on the border of screen or part of them are going off the screen.


> Please upload a screenshot of this happening and the offset numbers you are using


**--Here I uploaded them to imgur, idk if anyone still uses this but this is what we always uses back in minecraft's early days. I also added them under attachments incase that how you wish. I only did default mobs/creatures, I did, however; see that the entities take on the skins from the RS Pack I was using, and went to default and same thing was present. If you want me to upload ones from default RS Pack I will, and I should have done this from the start, but didn't think of it and all this has taken some time about 3 hours, but I will upload defaults if thats what u need.**
[](http://imgur.com/a/LSj7E)


Would it be possible to make a GUI like in BetterPVP mod that you can just drag the health and the Potion Effects to other areas of the screen?


> That sounds real cool, but unless one of the developers gets an itch to do it or someone provides a PR for that feature it is not likely to happen.


**--ok thanks**


Also I see no way to move the potion effects, I have looked and tried the in game Mod Options and the config file.


> The mod doesn't have potion effects, maybe you are seeing the vanilla ones that were added in later versions of MC.


**--lol to funny. Sorry i didn't know they added them. I don't play default and I ain't played since 1.8 just got back into it again.** 


One last thing if there was a setting to adjust the damage number and how it comes off the entity that would be cool too.


> What settings do you have in mind?


**--idk how it is written, if it is just an UI overlay or is there actually 3 dimensional depth
---if Overlay: i'd go with an option to have the numbers fly off of the entity from north "going up", south "going down", west and east in the same manner, for a start and the way the fly off the screen. Like an options for Bouncing off, flashing, like a heart beat, and the original, as is now, could even add on screen blood splashes as an option.
----if 3 dimensional depth: i'd say all of the above with taking into account the depth, and like an overlay blood mark or cut on the area of the entity that fades as the numbers disperse.**


Also if you could add a font for the numbers that has a border around if that would make them more legible.


> The numbers that come off the entity?


**--Yes. a black border around the numbers would make them more legible. I thought I was being over critical and so I asked my daughter, who is 9, and a minecraft nut, to come over and watch as I killed a bunch of spawned in entities and asked if she could see the numbers flying off, and she said no. so I knew it wasn't just me.  I use this effect to help things stand out a lot.**


### by PCGaming247
Thanks for everything. This is by no means to look down on your work. I love the mod and think that with out mods like this minecraft is lacking, I am just offering what I can, and who knows maybe some thing I say could get added in a update. smile. Hope this helps.


## ToroHealth Damage Indicators
[](https://mods.curse.com/mc-mods/minecraft/245733-torohealth-damage-indicators?comment=47)


### Screenshots
![2017-02-04_21 17 34](https://cloud.githubusercontent.com/assets/25558882/22623664/18924686-eb28-11e6-8621-1de1ff9acaa1.png)
![2017-02-04_21 19 14](https://cloud.githubusercontent.com/assets/25558882/22623669/189801f2-eb28-11e6-8e7e-318c323c2ac7.png)
![2017-02-04_21 20 10](https://cloud.githubusercontent.com/assets/25558882/22623668/18979d2a-eb28-11e6-8de6-b8ab30281cbe.png)
![2017-02-04_21 20 42](https://cloud.githubusercontent.com/assets/25558882/22623666/1895f83a-eb28-11e6-9b7f-d739646e2aac.png)
![2017-02-04_21 21 35](https://cloud.githubusercontent.com/assets/25558882/22623667/1896ffb4-eb28-11e6-9110-6f8d39919b1b.png)
![2017-02-04_21 22 24](https://cloud.githubusercontent.com/assets/25558882/22623665/1896177a-eb28-11e6-8521-11868ad88e92.png)
![2017-02-04_21 24 37](https://cloud.githubusercontent.com/assets/25558882/22623672/18a34670-eb28-11e6-9b6a-1f825598b2f2.png)
![2017-02-04_21 26 02](https://cloud.githubusercontent.com/assets/25558882/22623670/18a15a86-eb28-11e6-85e3-94acbca6437c.png)
![2017-02-04_21 26 22](https://cloud.githubusercontent.com/assets/25558882/22623673/18a6d1c8-eb28-11e6-92a6-29f6540307bf.png)
![2017-02-04_21 27 20](https://cloud.githubusercontent.com/assets/25558882/22623671/18a20c10-eb28-11e6-8c9a-ca697e5ec54c.png)

**Comment by frodare** [comment]
Nice screenshots!  Are you setting the health bar position to custom?  If you leave it in any of the other other modes it ignores the offsets.

**Comment by frodare** [comment]
The numbers seem pretty readable to me.  Maybe they are harder to see with the shader running, which looks pretty sweet btw.  

![2017-02-05_15 52 49](https://cloud.githubusercontent.com/assets/795621/22629809/56d6bc54-ebbb-11e6-8f4f-92f90317295f.png)

I do see how the bounce animation could be improved, especially when the numbers are close. They fly off the screen real fast.   The settings idea seems like a good idea too. I am planning to work on this project soon so I will see if I can come up with some improvements.

Thanks for your input!

**Comment by PCGaming247** [comment]
**1) For the positions I think I haven't tried changing  x and y in default, it was when i was moving everything around to make it feel right for the pack for the server, but im gonna check and I bet that is what it was.** 


**2) As for the Shaders and Picks comments thanks :) SEUS is still the best if your rig can run it maxed :) and I didn't even think that the shaders could be why it's hard to see the numbers for me so used to playing with them didn't even try default sry.**


**3) I'm glad you like the bounce idea and the settings :) can't wait to see what you will do with it.**


## -IDEA-
**One other thing that lots of people like from the old damage indicators was the optional skins you could have around the image. I liked those, but no one ever really made any others, all you see on everyone's videos is the default 3, oh and the purebd craft one that got popular. But if I remember correctly, it was not as simple as make you own png in this size and add to folder. That would be cool and could catch on. Another idea is you could have it come with a default skin pack, then people could make their own skins by adding them to that folder, for easy of use or, they could make there own skin packs by zipping them, and putting them in the folder. Let me know if you like this idea, I could help with the skin creation, I could make them to correspond with all the popular resource packs, so it could come with a default skin pack that will fit all players styles. --Just an Idea-- I didn't bring this one to the table the first time do to the fact that I like that your mod is different than the original damage indicators, but then after going over the post again I thought it could be done similar, yet still be different.**


**Thanks again for everything and can't wait to see that update :)**

**Comment by frodare** [comment]
I will look into the custom skin idea.  Any custom draft skins you would like to contribute would be greatly appreciated.  However, let me figure out how to do it and make a template for you to work off of first.

**Comment by zeriley** [comment]
A quick note on the font readability, ToroHealth uses the default font to render the damage numbers.  Because we are using the default, resource packs will affect the font of the numbers, which is something I hadn't considered when developing this.  So, we can maybe try to force the vanilla font, since it seems pretty readable.

**Comment by frodare** [comment]
@zeriley That is a very good point, I forgot that resources packs can override the fonts.

**Comment by frodare** [comment]
@PCGaming247 I have posted some custom skin template on this issue: https://github.com/ToroCraft/ToroHealth/issues/24

If you still want to create some custom skins, just upload them to that issue.  Thanks!
