### ISSUE TITLE
Damage numbers are not working correctly with Custom NPCs

### ISSUE THREAD

**Issue by frodare** [ToroCraft/ToroHealth#23]
https://mods.curse.com/mc-mods/minecraft/245733-torohealth-damage-indicators?comment=51

https://mods.curse.com/mc-mods/minecraft/245733-torohealth-damage-indicators?comment=50

**Comment by platinumphoenix2** [comment]
Just to add in more information:

Version of Custom NPCs: 1.10.2 (CustomNPCs_1.10.2(20nov16))

The issue occurs when you change the entity type of an NPC to a mob, like a spider.
Replicate by setting a Spider's health to anything but the default health - the health indicators start spamming.
(Spider's health is okay at 16 since that is the default health, but if you set it's health to any other number, the issue will start occurring).

**Comment by JayZX535** [comment]
I'm getting this in the CustomNPCs_1.11.2(10may17) version as well...

**Comment by Boolyman** [comment]
I came here looking for a solution to this as well.

**Comment by frodare** [comment]
I am working on a new mod, https://github.com/ToroCraft/ToroHUD, that is pretty much just ToroHealth but with a required server side component.  I think this problem might be easier to fix in it so I will test it and close this issue if I get the problem solved.

**Comment by frodare** [comment]
I just tested this on ToroHealth and ToroHUD with the latest CustomNPC mod and could not reproduce this issue.
