### ISSUE TITLE
Add HUD for Player + Positioning

### ISSUE THREAD

**Issue by Drehverschluss** [ToroCraft/ToroHealth#31]
Hello there first.

Found you mod a while ago and now since i mess around with mincraft again i miss some features.

1, Would be a Player Hud. I really want to get rid of all this BossBar health s*** things. :)
2, Indicators for effects. Like wither effect or heal effect. Also maby a Armor indicator. But thats probably a problem with some RPG plaugin wich changes Armor and there vallues, anyways.
3, Please give us the ability to "drag" the Hud to a position where we want it. I know we can change it in the config. But thats a pain if you change often from fullscreen to windowed.
4, Combatibility with other plugins like RPG Player Leveling. https://www.spigotmc.org/resources/rpg-player-leveling.11096
This plugin adds Damage Indicators via Holograms. And your Mod somehow changes the complete Hud to this Hologram massages. Heres a Picture wich shows exactly what happen. https://www.dropbox.com/s/12r4pznjvt86k7w/ToroIssue.png?dl=0 Also the Hud wont show after the first hit anymore when aiming the mob. Only appears when hitting with the Hologramm messages.

Just tell me if you need more information and if all that is even possible. 
MFG

**Comment by zeriley** [comment]
Thank you very much for your interest or in our mod.  Please see my comments on each suggestion below.

1. Unfortunately, this is outside of the scope of our mod at this time.
2. In order to get this information, as well as potion effects (which we've wanted to include for a while), we would need to make this a server-side mod, as well, and our intention is to keep this client-side only.
3. I understand the utility and convenience of such a feature, but it too is outside of scope.  It would take an incredible amount of time to implement such a feature.
4. This looks like an issue with the implementation of the holograms by the other mod.  No easy fix for this.

Thanks again for your interest and I apologize that we are unable to fulfill your requests at this time.

**Comment by Drehverschluss** [comment]
Allright no problem at all.
Thanks for answering.
