### ISSUE TITLE
Toro Health conflict with Scaling Health as of ScalingHealth-1.16.5-4.1.1+7

### ISSUE THREAD

**Issue by ExiledMiner04** [ToroCraft/ToroHealth#94]
When having both in a world, multiple problems arise:

1. Mobs get health set to NaN/health or Health Over/0 eventually will fix itself.
2. health bar of entity will be extra long instead (other reports shown this one, may be unrelated).
3. When Scaling Health difficulty is above 0, mobs will one shot the player and cause a death bug where you can't loot or even get a death screen. Your hearts will become 0 or even NaN and you can't die anymore to any sources and can pass through mobs, screen will shake uncontrollably.
![2021-05-21_11 36 06](https://user-images.githubusercontent.com/79032632/120079818-ab2c7b80-c083-11eb-9635-bd7d6959dafb.png)
![2021-05-21_12 09 54](https://user-images.githubusercontent.com/79032632/120079821-acf63f00-c083-11eb-890b-4af0c1d2da50.png)
![2021-05-19_17 59 00](https://user-images.githubusercontent.com/79032632/120079854-ddd67400-c083-11eb-9dd8-dde27c6d9873.png)

**Comment by frodare** [comment]
This is a bit tricky.  Anything that alters the health numbers will likely disrupt this mod.  ToroHealth has to do some work-arounds to get the health bar working because it doesn't have a server side component, which is one of the design requirements of the project.  You might want to try a health mod that is also installed on the server, maybe it wouldn't have the same issue.
